[build-system]
requires = ["setuptools", "setuptools-scm", "Cython", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "adder"
dynamic = ["version", "requires-python"]

[tool.setuptools_scm]
